ALTER TABLE "College" ADD COLUMN IF NOT EXISTS "officialWebsite" TEXT;
ALTER TABLE "College" ADD COLUMN IF NOT EXISTS "sourceUrl" TEXT;
ALTER TABLE "College" ADD COLUMN IF NOT EXISTS "dataVerifiedAt" TIMESTAMP(3);
ALTER TABLE "College" ADD COLUMN IF NOT EXISTS "nirfRank" INTEGER;
ALTER TABLE "College" ADD COLUMN IF NOT EXISTS "nirfScore" DOUBLE PRECISION;
ALTER TABLE "College" ADD COLUMN IF NOT EXISTS "dataNote" TEXT;
